# @package _global_
defaults:
  - oc_base
  - /prior: gauss_truncate
  - /sde: vp_10
  - /model@generative_ctrl: lerp
  - /model@inference_ctrl: clipped
  - /loss: time_reversal
  - _self_

# Solver
solver:
  _target_: sde_sampler.solver.oc.Bridge

train_batch_size: 2048

# Model
generative_ctrl:
  clip_score: 10.
  clip_model: 10.

inference_ctrl:
  name: inference_ctrl
  clip_model: 10.